version: "3.9"

services:
  redis:
    image: redis:7.4-alpine
    container_name: redis_container

    env_file:
      - .env

    ports:
      - "6380:6379"

    volumes:
      - ./redisdata:/data

    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        cat <<EOF > /usr/local/etc/redis/users.acl
        user default off
        user ${REDIS_USER} on >${REDIS_USER_PASSWORD} ~* +@all
        EOF

        cat <<EOF > /usr/local/etc/redis/redis.conf
        bind 0.0.0.0
        appendonly yes
        aclfile /usr/local/etc/redis/users.acl
        EOF

        redis-server /usr/local/etc/redis/redis.conf
      '

    healthcheck:
      test: ["CMD", "redis-cli", "--user", "${REDIS_USER}", "-a", "${REDIS_USER_PASSWORD}", "PING"]
      interval: 30s
      timeout: 10s
      retries: 5

    restart: unless-stopped